CREATE EVENT IF NOT EXISTS delete_audience
  ON SCHEDULE
     EVERY 12 HOUR
  ON COMPLETION PRESERVE
  ENABLE
  COMMENT 'DELETE AUDIENCE'
  DO
    DELETE FROM audience WHERE start_date IS NULL AND 0 > TIMESTAMPDIFF(SECOND, NOW(), DATE_ADD(input_date, INTERVAL + 7 day));

CREATE EVENT IF NOT EXISTS initialize_schedule
  ON SCHEDULE
    EVERY 1 MONTH STARTS '2019-09-01 00:00:00'
  ON COMPLETION PRESERVE
  ENABLE
  COMMENT 'INITIALIZE SCHEDULE'
  DO
    UPDATE schedule SET first_time = 1, second_time = 1;
